### ISSUE TITLE
README is too big. Should have Table of Contents at the beginning 

### ISSUE THREAD

**Issue by AshBardhan** [approachable-io/software-interview-prep#106]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT
As explained the README content is too much. It's hard to navigate sometimes. 

### EXPECTED BEHAVIOR
There should be some Table of Contents section at the beginning of the README. It can be generated automatically using [this plugin](https://github.com/jonschlinkert/markdown-toc) or add the headers manually for the time being.

**Comment by LukeSchlangen** [comment]
I love this! Great suggestion @AshBardhan! I'll give it a few labels!

**Comment by AshBardhan** [comment]
I'll take up this task and redesign `README.md`. Should it automate or manually add the table of contents?

**Comment by LukeSchlangen** [comment]
I'm fine with either one. Does automate require some sort of build process? I'd say the simpler the better, so I think manual is good.

**Comment by izulien** [comment]
I am curious how the automation would be too.  If it is purely based on heading tags that would be pretty great.  If it is some other manner then we would probably want to avoid the extra complication.

**Comment by AshBardhan** [comment]
Only heading based. Just follow the convention. That plugin takes care itself.

**Comment by LukeSchlangen** [comment]
Cool! Yeah, as long as it doesn't add complexity, that sounds pretty sweet!

**Comment by AshBardhan** [comment]
@LukeSchlangen Added a PR on this issue. Take a look.
Plus, I've added `package.json` file and improved your `.gitignore` file.

**Comment by LukeSchlangen** [comment]
Thanks @AshBardhan!
