### ISSUE TITLE
Improve description of the Fizz Buzz question and add an answer

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#11]
The `Fizz Buzz` question on [fizz-buzz.html](http://interview.approachable.io/views/questions/whiteboard/fizz-buzz.html) to include a better description of the classic Fizz Buzz problem.

Adding an answer (in the language of your choosing or maybe even pseudo-code or an image of a whiteboard/paper or video) would be a great addition!

**Comment by Jeff-Duke** [comment]
I can take this if it's still available

**Comment by LukeSchlangen** [comment]
@Jeff-Duke Please do!

**Comment by Jeff-Duke** [comment]
I took a shot at it, opened PR #12 Let me know if there's anything you'd like me to change.
