### ISSUE TITLE
Back to Top / Back to TOC Links for README

### ISSUE THREAD

**Issue by izulien** [approachable-io/software-interview-prep#115]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

Would love to have a "Back to Top" or "Back to TOC" type of link at each section to add to the easy navigation @AshBardhan built out.

### EXPECTED BEHAVIOR

Click a section link from the table of contents and be able to quickly jump back up to the table with a quick link at each section.

**Comment by LukeSchlangen** [comment]
Resolved by #122
