### ISSUE TITLE
Incorrect Link on Questions.html for Data Science Overview

### ISSUE THREAD

**Issue by izulien** [approachable-io/software-interview-prep#116]
### ISSUE TYPE
* [ ] Typo      
* [x] Bug       
* [ ] Feature   

### WHERE / WHAT

Link on `technical.html` doesn't load the new `data-science.html` question.

### EXPECTED BEHAVIOR

The `Data Science` question should link to the local repository's file for data science instead of the forked copy.

### REPRODUCTION STEPS

1. Visit [interview.approachable.io](http://interview.approachable.io/)
2. Choose the [View our list of technical questions](http://interview.approachable.io/views/technical.html) link
3. Follow the [Data Science Overview](https://github.com/syedbilal5000/software-interview-prep/blob/master/views/questions/technical/data-science.html) link

You will find yourself at @syedbilal5000's repo instead of the [question's HTML page](http://interview.approachable.io/views/questions/technical/data-science.html) in this repo.

**Comment by syedbilal5000** [comment]
Sorry for that, corrected url.
Thanks.

**Comment by izulien** [comment]
@syedbilal5000 Did you make a PR for this?

**Comment by syedbilal5000** [comment]
Yes, I made PR.

**Comment by LukeSchlangen** [comment]
Thank you!
