### ISSUE TITLE
Inconsistency with "More technical interview questions" link in "CRUD" question

### ISSUE THREAD

**Issue by izulien** [approachable-io/software-interview-prep#117]
### ISSUE TYPE
* [ ] Typo      
* [x] Bug       
* [ ] Feature   

### WHERE / WHAT

The "More technical interview questions" link is the same size as the heading instead of being standard size in @mike8161990's database/SQL question about `CRUD`.
![image](https://user-images.githubusercontent.com/14319924/32301971-ac17d6ea-bf36-11e7-8f0e-6f7982ba5cd3.png)

### EXPECTED BEHAVIOR

The link should be the same size as standard text as with other questions.
![image](https://user-images.githubusercontent.com/14319924/32302018-ed69ab5a-bf36-11e7-98df-016b5026a3fd.png)

**Comment by LukeSchlangen** [comment]
Thanks @mike8161990 for resolving this!
