### ISSUE TITLE
Resize logo to decrease page load time.

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#14]
Create a smaller version of the logo, but don't remove the current one. Then change the references to the new smaller (and ideally optimized) version.

The largest version of the logo we actually use on the site is just 20px wide, so it can be shrunk to that size. Then compressed using the steps laid out here https://developers.google.com/speed/docs/insights/OptimizeImages

**Comment by chridgely** [comment]
Hi! First time contributor, I'd like to make this change

**Comment by LukeSchlangen** [comment]
Go for it @chridgely! We'd love to have you on board!

**Comment by TechiePriyaRanjan** [comment]
Please check the updated PR, I've updated the logo size from 22.4 KB to 1.04 KB

**Comment by LukeSchlangen** [comment]
Hi @TechiePriyaRanjan, what is the number for that PR? I can't seem to find it.

**Comment by TechiePriyaRanjan** [comment]
#16 , I just forget to make PR and merged it with me mine itself 🏷 
Now it's reflected in PR tab :)

**Comment by LukeSchlangen** [comment]
Thanks @TechiePriyaRanjan! @chridgely, I'm going to close this issue. If you'd like to grab another, we can definitely still use your help! https://github.com/approachable-io/software-interview-prep/issues
