### ISSUE TITLE
Moving `dependency installation` section of README to supplemental documentaion

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#18]
Move the [dependency installation](https://github.com/approachable-io/software-interview-prep#install-dependencies) section to the `supplemental-documentation` folder to keep only critical instructions in the README (to keep things clear and simple without requiring a `node` install).

Put a link in the main guide for those interested in learning more (something like, "At this point, many projects will require installing dependencies, click here to learn more").

**Comment by VestigeJ** [comment]
May I?

**Comment by LukeSchlangen** [comment]
Thanks @VestigeJ and @chridgely!
