### ISSUE TITLE
More detailed instructions around making changes to a project in VS Code or Atom

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#22]
Right now, for instructions on making changes we basically just tell the user to ["make changes"](https://github.com/approachable-io/software-interview-prep#making-your-changes). This makes sense to people who have been doing development for a while, but is super confusing to someone new to software.

Specifically, this guide should show a user how to add a new whiteboard question or add a new technical question. This involves:

1. Adding a new `html` file
2. Adding a link to that html file to its respective `whiteboard.html` or `technical.html`

Right now, the details suggest using an IDE, but I think we should be more explicit and tell the person following the guid (and potentially using GitHub or writing code for the very first time), exactly how to do this in detail with a specific editor. We can add more editors later, but I'd like to have one of these examples done in a free, approachable (no emacs or vim), editor like Atom or VS Code.

**Comment by travisbartholome** [comment]
I can do this for Atom since it's what I normally use. Do you want this in a stand-alone `.md` file or as part of the README?

**Comment by LukeSchlangen** [comment]
Separate (in the `supplemental-documentation`) would be perfect! Probably a slight adjustment to the main README to link to it and encourage users to go there for more details. Thank you!

**Comment by izulien** [comment]
I am just setting up VS Code myself.  I'll see if I can write up a supplemental document in a similar fashion to the one created by @travisbartholome.  

If everything works as expected I should have a PR in later today or early tomorrow morning.

**Comment by LukeSchlangen** [comment]
That would be awesome @izulien! I'll reopen!

**Comment by izulien** [comment]
PR added in.

**Comment by izulien** [comment]
@LukeSchlangen How do you want to reflect the VS Code Editor docs to the Read Me?

> ### Making your changes
> 
> Now that we have our own branch, we can make our changes. There are two ways to edit files, either in GitHub, or with a text editor on your computer. Open the file containing the code in a code editor. You can use any code editing program you are comfortable with, popular choices are Atom, VS Code, and Sublime Text.
> 
> See [this document](../blob/master/supplemental-documentation/using-atom.md) for more information
> about using the Atom text editor to create new files and add them to the main lists of
> interview questions. Even if you aren't using Atom, this document outlines the
> general process for adding a new problem.

- We could put the link on the first paragraph at the mention of Atom and VS Code.  Though users may think it links to their downloads sites.
- We could update the "See this document" line to simply reflect "See [Using Atom](../blob/master/supplemental-documentation/using-atom.md) or [Using VS Code](../blob/master/supplemental-documentation/using-vs-code.md) for more information about using a text editor to create new files and add them to the main lists of interview questions."

I believe the second bullet seems to make the most sense but I'll let you decide how you want the layout to fall.

**Comment by LukeSchlangen** [comment]
Good thinking. I think the second one makes the most sense too. If you want, you could add a statement about how, "People spend a lot of time choosing their favorite text editor, but don't get stuck here, Atom and VS Code are both great options, so we recommend simply picking one quickly."

The biggest concern I have with more choice here is putting people into analysis paralysis.

**Comment by izulien** [comment]
I can add it in.  This project as a whole is helping me get more familiar with GIT in general.  I just did a squash of my commits for my last PR.

I do agree, adding a "just pick one and go" type line would work pretty well.
