### ISSUE TITLE
Supplemental Documentation Correction - using-atom.md needed

### ISSUE THREAD

**Issue by izulien** [approachable-io/software-interview-prep#25]
Error in directory notes

> The last step is to add your question to the main list. If you wrote a whiteboard question, this list will be in views/questions/whiteboard.html; technical questions go in views/questions/technical.html.

![Screencap of views directory](https://user-images.githubusercontent.com/14319924/31856319-ffcf5708-b68b-11e7-8fff-eefc692e97ab.png)

This should read The last step is to add your question to the main list. If you wrote a whiteboard question, this list will be in **views/whiteboard.html**; technical questions go in **views/technical.html**.

**Comment by izulien** [comment]
I can make the correction in about an hour.  Just didn't want to forget about it.

**Comment by travisbartholome** [comment]
Whoops, sorry about that. I'll let you make the change.

**Comment by izulien** [comment]
No worries, I used your doc as a template which allowed me to find the error.  Basically just worked as a double review.

I'm still debating which I like better between Atom and VS Code and going through your setup at least helps highlight some differences.

**Comment by LukeSchlangen** [comment]
@izulien and @travisbartholome, you two are amazing! Thank you so much!
