### ISSUE TITLE
New Feature - Update project to include community guidelines

### ISSUE THREAD

**Issue by izulien** [approachable-io/software-interview-prep#27]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE

Project's [Community Profile](https://help.github.com/articles/viewing-your-community-profile/) will track this progress 

### EXPECTED BEHAVIOR

Completing the Community profile for the project.  Adding in templates and overall guidelines will help [Build a strong community](https://help.github.com/categories/building-a-strong-community/)

- [x] Description of Project
- [x] README
- [x] [Code of Conduct](https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/)
- [x] [Contributing Guidelines](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
- [x] License
- [x] [Issue Template](https://help.github.com/articles/creating-an-issue-template-for-your-repository/)
- [x] [Pull Request Template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/)

### REPRODUCTION STEPS

I propose we add these items to a `/docs/` directory to keep the root as clean as possible.  The other option supported by GitHub is `/.github/` which may not be intuitive or visible for users not familiar with hidden directories.

If interested, I have some starter templates for both Issues and PR that could be added in with minimal effort.  If they turn out to bring no additional value the files can always be removed after.

If interested in learning more or you need ideas: [Open Source Guides](https://opensource.guide/)

**Comment by LukeSchlangen** [comment]
Yes please! I think `/docs/` is the right call. Because the "guiding light" of all of our projects is approachability, I'd like for our `CONTRIBUTING.md` to reflect that.

I'm not sure what type of contributions make the most sense for our organization. Our [project-list](https://github.com/approachable-io/project-list) repository has the following language, but I'm not sure how to convert this to a `CONTRIBUTING.md` or if there is one out there that seems like a good fit. I'd love some guidance on this.

> ### An Approachable Open Source project will:
> 
> - allow those who are interested and committed, regardless of skill level, contribute to the project.
> - have at least one approachable issue that can be worked on without end and a guide for how to work on the issue so that a newcomer can always feel comfortable making their first pull request. We call this the `Infinitely Approachable Issue`. An excellent example of this can be found in the [getting-started](https://github.com/approachable-io/getting-started) repository.
> 
> Every project has tradeoffs, and that is OK as long as we're on the same page. An Approachable Open Source project will often:
> 
> - sacrifice development speed, performance, and productivity every time if it makes the code easier for those with less technical expertise to participate in the project.
> - Write Everything Twice (WET) instead of following the coding standard of Don't Repeat Yourself (DRY).
> 
> Of course, performant and DRY code written at a fast pace is still preferable to WET code written at a slow pace, but not at the cost of making a project less approachable. This may make an Approachable Open Source project less apealling to some highly-skilled developers, but that is OK with Approachable IO. There are plenty of open source projects to push the technical limits of experts, we are filling a different purpose.

**Comment by izulien** [comment]
With that in mind I'll add a commented note to the proposed Issue and PR templates that lets the users know it isn't really required data, instead it is a guide to help provide more info up front for all.

As far as the `CONTRIBUTING.md` document I think using something like @nayafia's [contributing-template](https://github.com/nayafia/contributing-template/blob/master/CONTRIBUTING-template.md) would be a great start.  You could even bring the WET vs DRY into the contributing file letting new contributions are always welcome and they shouldn't be afraid to get a little WET ;).

I'm adding a guidelines branch to my fork and will push some general outlines that could be used.  That should help get a foundation in place and perhaps spark ideas for any future changes.

**Comment by LukeSchlangen** [comment]
That sounds terrific. I really like sharing best practices without enforcing them. That way we can still allow new people to contribute while they learn.

Also, I love the "don't be afraid to get a little WET". That's totally the spirit of being approachable. Try doing things the right way, but don't be afraid to make mistakes.

**Comment by izulien** [comment]
Updated with the basics. It will likely need a review for grammar and spelling.  I did catch about 3 errors before submitting.

It is also worth noting, the issues link in contributions points to this repository issues listing, not the main approachable-io account.

**Comment by LukeSchlangen** [comment]
I didn't catch any spelling errors, but I did have a few suggestions in my review.

As far as the issues link goes, I think that's probably the correct link. I think each repository should probably refer to its own issues page.

**Comment by izulien** [comment]
These are all in play now.  Case Closed until need for edits/changes come up.

**Comment by LukeSchlangen** [comment]
Thanks @izulien, forgot to close this when I merged the PR!
