### ISSUE TITLE
Add detail to README for adding a new interview question

### ISSUE THREAD

**Issue by ziyadedher** [approachable-io/software-interview-prep#38]
Note that the new question `.html` file should just be copied from an existing one in its respective `/questions/technical/` or `/question/whiteboard/` folder and modified accordingly to maintain consistency.

Note that the created technical or whiteboard question must be added to the respective `whiteboard.html` or `technical.html` file.

Note that the `<title>` and `<h1>` tags of the copied file must be changed to represent the new question.

Supported by #33

**Comment by LukeSchlangen** [comment]
Thank you @ziyadedher! I think these notes will help our experienced users (who won't be using the `VS Code` or `Atom` guides remember every component of what needs to be done when adding a new quesiton.

**Comment by izulien** [comment]
I can make these changes when I update #22 to include the VS Code link.

**Comment by LukeSchlangen** [comment]
Sounds good! That makes sense since it will be in the same section you're already editing. Why don't you plan to take it unless we hear from someone else!
