### ISSUE TITLE
Need relatively new Github users to test tutorial

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#4]
We're creating a guide to making Pull Requests on projects and we would love feedback. If you're totally new to Github or Pull Requests, I would suggest starting with our [getting-started](https://github.com/approachable-io/getting-started) guide.

If you are somewhat familiar with Github, we would love for you to follow [the guide for this repository](https://github.com/approachable-io/software-interview-prep) and add an issue or create a Pull Request for anything you find to be confusing. This is a work in progress, so please, if there's a point in the guide where you get stuck or even a point that took longer than you think it should have to figure out, let us know!

**Comment by EstebanDalelR** [comment]
Hey!
Experienced user here. Made a couple PRs to the Readme, included links directly to actions. This will help users navigate _without_ having to shuffle around.

**Comment by techboy14** [comment]
i will test it

**Comment by LukeSchlangen** [comment]
Thanks @techboy14!

**Comment by christophermoura** [comment]
Hi there, @LukeSchlangen!

I'm testing this tutorial.
I hope I can contribute to this fine project!
