### ISSUE TITLE
Create 404.html for website

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#43]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT
Right now, going to a route that doesn't exist will show a generic github 404 message

<img width="1392" alt="screen shot 2017-10-23 at 1 10 51 pm" src="https://user-images.githubusercontent.com/5384581/31905667-8cac9910-b7f4-11e7-8779-bd97a9772cd9.png">

It would be better to have a custom 404 message (information about approachable.io and how to get involved in this project) as well as the 404 message.

### EXPECTED BEHAVIOR
visiting a link that doesn't exist (eg http://interview.approachable.io/qwerty) should display our custom 404.html

### REPRODUCTION STEPS
I would suggest starting with this document:
https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by techboy14** [comment]
I will help

**Comment by LukeSchlangen** [comment]
This has been added thanks to @talitaoliveira! It could probably be enhanced with links to other pages (to help a user regain their footing), so I'll create a new issue for that.
