### ISSUE TITLE
Default README should suggest `git add .` first

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#45]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

We suggest `git add README.md` instead of suggesting `git add .` and then we explain that `.` is an option. We should reverse this since most of our users will likely be using `git add .` and not selecting individual files to commit.

**Comment by benzittlau** [comment]
Taking a look at this.
