### ISSUE TITLE
Add "Return largest number in array" whiteboard question

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#46]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

This is a question that comes up often (or ones like it) in interviews. It would be good to add this to our collection

### EXPECTED BEHAVIOR

We should add this page (follow the guide in the README) to the application

**Comment by hkdeman** [comment]
Let me take a look at this! :D
