### ISSUE TITLE
Add relevant links to 404.html

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#50]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

Users on our 404 page don't have suggestions on what to do next. We should probably provide suggestions on where they might want to go.

### EXPECTED BEHAVIOR

Users who end up on our 404 page should be given links back to our `index.html` and possibly be told a little more about the organization.

### REPRODUCTION STEPS

visit http://www.approachable.io/404 to see current state. Would like similar functionality, but with links to suggested content.

**Comment by andyvh** [comment]
I can do this! Is it claimed yet?

**Comment by LukeSchlangen** [comment]
Thanks!
