### ISSUE TITLE
Add "Return largest number in array" whiteboard question solution

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#51]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

This is a question that comes up often (or ones like it) in interviews. It would be good to add an answer to this to our collection. It currently has an approach, so this is probably a matter of embedding a github gist like our other questions.

**Comment by hkdeman** [comment]
Doing it! Forgot it on the first shot!

**Comment by LukeSchlangen** [comment]
Thanks @hkdeman
