### ISSUE TITLE
update Class vs Object

### ISSUE THREAD

**Issue by nvinayvarma189** [approachable-io/software-interview-prep#76]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

--> Class vs object question in technical question
### EXPECTED BEHAVIOR

Add more information about class vs object as the newbies won't understand a thing by reading that one line

### REPRODUCTION STEPS

#

**Comment by LukeSchlangen** [comment]
Looks like you made a few PRs for this. I'll go ahead and close it.
