### ISSUE TITLE
Documentation Review: Moving `dependency installation` and `creating a branch` to supplemental documentation

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#8]
If you are new to this project and [approachable.io](http://www.approachable.io), we would love your feedback (first time contributors welcome)!

I went back through our guide today and I think the [dependency installation](https://github.com/approachable-io/software-interview-prep#install-dependencies) and [creating a branch](https://github.com/approachable-io/software-interview-prep#creating-a-branch) sections are well written, but I think it might make the guide less approachable for new users. We have a `supplemental-documentation` folder that could be used to store these sections. We could put links in the main guide for those interested in how to do things the right way?

@redxtech I would love your thoughts on this. I think it's definitely best practice to create a new branch, but I'm worried that it could make the project less approachable. This project in particular will probably remain `npm install` free in order to maintain approachability, so I'm not sure that the section is necessary here. It could be something we include in a later guide? The plan is to build to more and more complex topics. Is there maybe a balance where we add this as supplemental material like a `suggested best practice` instead of including it in the main guide?

**Comment by redxtech** [comment]
I agree with the installing dependencies section being moved, that makes sense. However, the concept of branches is quite simple, and essential enough that I do not think it necessary to move it to the `supplemental-documentation` folder. I could link to a few articles that I find that describe branches in detail if it's confusing.

I do like the idea of having a document dedicated to best practices, that sounds useful, and something that would make for a good addition.

**Comment by LukeSchlangen** [comment]
Sounds good! I'll make an issue to move the `installing dependencies` section. We'll leave the branching for now and wait for feedback.

**Comment by redxtech** [comment]
Sounds like a good plan.
