### ISSUE TITLE
Name 3 ways to decrease page load (perceived or actual load time).

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#87]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

Our technical interview questions are a little light on `technical.html`. It would be good to add this question to our list.

### EXPECTED BEHAVIOR

Clicking a link will take you to the question page which will allow you to see a possible response to the question.

### REPRODUCTION STEPS

To create this new question, you should be able to follow the guide in the README [https://github.com/approachable-io/software-interview-prep](https://github.com/approachable-io/software-interview-prep)

**Comment by viralvin** [comment]
I'll take this one. I'm looking for bugs today to close out Hacktoberfest.

**Comment by LukeSchlangen** [comment]
Added! Thanks @viralvin!
