### ISSUE TITLE
Add headings for technical questions page categories

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#88]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

We're getting quite a few contributions (and merge conflicts) because everyone is adding questions to the bottom of the list. Moving the questions into categories would help us avoid this problem. Maybe these could have links at the top the would skip down to certain sections of the page (based on `id`s?), but that could be a separate issue.

### EXPECTED BEHAVIOR

Questions on `technical.html` would be divided into categories like:
JavaScript
C#
Java
Agile / Scrum
HTML
CSS
ANGULARJS
OOP
NODE

with corresponding questions underneath them.

### REPRODUCTION STEPS

Currently technical.html is just a list without any categories, adding categories will allow it to be searchable to those interested in specific topics.

**Comment by juanluischaurant** [comment]
I got this one!

**Comment by milanojs** [comment]
is this ready?

**Comment by LukeSchlangen** [comment]
I haven't seen a PR for this. @juanluischaurant, could you let us know if you are still planning to tackle this one? Otherwise @milanojs, feel free to jump on it.

**Comment by juanluischaurant** [comment]
Yes, I am working on it, but I had troubles with my internet connection. 
I am so sorry for my delay.

**Comment by LukeSchlangen** [comment]
Closed by #98
