### ISSUE TITLE
Fix link text on whiteboard.html

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#9]
The text for the whiteboard link on `whiteboard.html` reads `What is the difference between a class and an object?` when it should read `Fizz Buzz`. We need someone to fix the text.

http://interview.approachable.io/views/whiteboard.html

**Comment by bryancresswell** [comment]
Done!

**Comment by LukeSchlangen** [comment]
Great work @bryancresswell! Thank you for your contribution! If you want to take a look at any of the [other issues](https://github.com/approachable-io/software-interview-prep/issues), we'd love your help!
