### ISSUE TITLE
New Question: What are differences between compiled and interpreted languages? Name an example of each.

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#90]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

Our technical interview questions are a little light on `technical.html`. It would be good to add this question to our list.

### EXPECTED BEHAVIOR

Clicking a link will take you to the question page which will allow you to see a possible response to the question.

### REPRODUCTION STEPS

To create this new question, you should be able to follow the guide in the README [https://github.com/approachable-io/software-interview-prep](https://github.com/approachable-io/software-interview-prep)

**Comment by LukeSchlangen** [comment]
Closed thanks to #95 and #94. Thanks @mare80!

**Comment by amberjohnsonsmile** [comment]
Just submitted a PR for this!
