### ISSUE TITLE
Add New JavaScript Question: What's a typical use case for anonymous functions?

### ISSUE THREAD

**Issue by LukeSchlangen** [approachable-io/software-interview-prep#91]
### ISSUE TYPE
* [ ] Typo      
* [ ] Bug       
* [x] Feature   

### WHERE / WHAT

Our technical interview questions are a little light on `technical.html`. It would be good to add this question to our list.

### EXPECTED BEHAVIOR

Clicking a link will take you to the question page which will allow you to see a possible response to the question.

### REPRODUCTION STEPS

To create this new question, you should be able to follow the guide in the README [https://github.com/approachable-io/software-interview-prep](https://github.com/approachable-io/software-interview-prep)

**Comment by milanojs** [comment]
Hi! do we have the answer? o i need to create one?

**Comment by LukeSchlangen** [comment]
You need to create one to add the question. There are several good answers online.

If you would prefer a different question, feel free to add any you think are relevant!

**Comment by glebkema** [comment]
I guess that this issue should be closed, because [the answer](https://github.com/approachable-io/software-interview-prep/blob/master/views/questions/technical/anonymous-functions.html) has already been added by #121.
Or the wording of the problem must be updated.

**Comment by LukeSchlangen** [comment]
I think it can be closed. If you would like to improve the wording, I think that would make for a good PR as well! Thank you for pointing this out!
